import type { CachingOptions } from '#domain/caching';
import type { HttpOptions } from '#domain/clients';
import type { KeyDictionary, KeyStringDictionary } from '#domain/utils';

/**
 * Enum representing the source of a client response.
 */
export enum ClientResponseSource {
  /** The response was fetched from a remote server. */
  remote = 'remote',
  /** The response was retrieved from a cache. */
  cache = 'cache',
  /** The response was generated locally. */
  local = 'local',
  /** The response was generated by a CLI tool. */
  cli = 'cli'
}

/**
 * Represents a generic client response.
 * @template TStatus The type of the status.
 * @template TData The type of the data.
 */
export type ClientResponse<TStatus, TData> = {
  /** The source of the response. */
  source: ClientResponseSource;
  /** The status code or message. */
  status: TStatus;
  /** The response data. */
  data: TData;
  /** Whether the request was rejected. */
  rejected?: boolean;
}

/**
 * Feature keys used for HTTP configuration.
 */
export enum HttpFeatures {
  /** Whether to use strict SSL certificate validation. */
  StrictSSL = 'strictSSL'
}

/**
 * Options for the HTTP client.
 */
export type HttpClientOptions = {
  /** Caching options. */
  caching: CachingOptions,
  /** HTTP-specific options. */
  http: HttpOptions,
}

/**
 * Represents an HTTP client response.
 */
export type HttpClientResponse = ClientResponse<number, string>;

/**
 * Supported HTTP request methods.
 */
export enum HttpClientRequestMethods {
  /** GET method. */
  get = 'GET',
  /** HEAD method. */
  head = 'HEAD'
}

/**
 * Represents a dictionary of query parameters.
 */
export type QueryDictionary = KeyDictionary<string | number | boolean>

/**
 * Function signature for making an HTTP client request.
 */
export interface THttpClientRequestFn {
  (
    url: string,
    query?: QueryDictionary,
    headers?: KeyStringDictionary,
  ): Promise<HttpClientResponse>;
}

/**
 * Interface for an HTTP client.
 */
export interface IHttpClient {
  /** Performs a GET request. */
  get: THttpClientRequestFn;
}

/**
 * Represents a JSON client response.
 * @template TData The type of the parsed JSON data.
 */
export type JsonClientResponse<TData> = ClientResponse<number, TData>;

/**
 * Interface for a client that handles JSON requests and responses.
 */
export interface IJsonHttpClient {
  /** The underlying HTTP client. */
  httpClient: IHttpClient;
  /**
   * Performs a GET request and parses the response as JSON.
   * @template TData The expected type of the JSON data.
   */
  get<TData = KeyDictionary<any>>(
    url: string,
    query?: QueryDictionary,
    headers?: KeyStringDictionary,
  ): Promise<JsonClientResponse<TData>>;
}

/**
 * Represents a response from a shell command.
 */
export type ShellClientResponse = ClientResponse<string, string>;

/**
 * Function signature for making a shell client request.
 */
export interface ShellClientRequestFn {
  (
    cmd: string,
    args: Array<string>,
    cwd: string,
  ): Promise<ShellClientResponse>
}

/**
 * Interface for a shell command client.
 */
export interface IShellClient {
  /** Executes a shell command. */
  request: ShellClientRequestFn;
}

/**
 * Represents the structure of a GitHub tags API result.
 */
export type GithubTagsApiResult = [{ name: string }]

/**
 * Represents the structure of a GitHub commits API result.
 */
export type GithubCommitsApiResult = [{ sha: string }]

/**
 * Represents the processed GitHub JSON client response.
 */
export type GithubJsonClientResponse = JsonClientResponse<string[]>