export type CodeLens = import("vscode").CodeLens;
export type ConfigurationChangeEvent =
  import("vscode").ConfigurationChangeEvent;
export type Diagnostic = import("vscode").Diagnostic;
export type DiagnosticCollection = import("vscode").DiagnosticCollection;
export type DiagnosticSeverity = import("vscode").DiagnosticSeverity;
export type Disposable = import("vscode").Disposable;
export type DocumentFilter = import("vscode").DocumentFilter;
export type DocumentSelector = import("vscode").DocumentSelector;
export type EventEmitter<T> = import("vscode").EventEmitter<T>;
export type ExtensionContext = import("vscode").ExtensionContext;
export type OutputChannel = import("vscode").OutputChannel;
export type QuickPickItem = import("vscode").QuickPickItem;
export type Range = import("vscode").Range;
export type RelativePattern = import("vscode").RelativePattern;
export type Task = import("vscode").Task;
export type TaskExecution = import("vscode").TaskExecution;
export type TextDocument = import("vscode").TextDocument;
export type TextDocumentChangeEvent = import("vscode").TextDocumentChangeEvent;
export type Uri = import("vscode").Uri;
export type WorkspaceConfiguration = import("vscode").WorkspaceConfiguration;
export type WorkspaceEdit = import("vscode").WorkspaceEdit;
export type WorkspaceFolder = import("vscode").WorkspaceFolder;

export declare const CodeLens: typeof import("vscode").CodeLens;
export declare const Diagnostic: typeof import("vscode").Diagnostic;
export declare const EventEmitter: typeof import("vscode").EventEmitter;
export declare const FileType: typeof import("vscode").FileType;
export declare const Range: typeof import("vscode").Range;
export declare const RelativePattern: typeof import("vscode").RelativePattern;
export declare const TextDocumentChangeReason: typeof import("vscode").TextDocumentChangeReason;
export declare const Uri: typeof import("vscode").Uri;
export declare const WorkspaceEdit: typeof import("vscode").WorkspaceEdit;
export declare const commands: typeof import("vscode").commands;
export declare const env: typeof import("vscode").env;
export declare const extensions: typeof import("vscode").extensions;
export declare const languages: typeof import("vscode").languages;
export declare const tasks: typeof import("vscode").tasks;
export declare const window: typeof import("vscode").window;
export declare const workspace: typeof import("vscode").workspace;
