#!/usr/bin/env python3
"""Shared audit rules and classifications."""

from __future__ import annotations

import re

SOURCE_EXTENSIONS = {
    ".adb",
    ".ads",
    ".asm",
    ".bas",
    ".bash",
    ".c",
    ".c3",
    ".cbl",
    ".cc",
    ".clj",
    ".cljs",
    ".cljc",
    ".cob",
    ".cobol",
    ".cpp",
    ".cpy",
    ".cr",
    ".cs",
    ".cshtml",
    ".cjs",
    ".cts",
    ".cxx",
    ".d",
    ".dart",
    ".erl",
    ".escript",
    ".ex",
    ".exs",
    ".f",
    ".f03",
    ".f08",
    ".f77",
    ".f90",
    ".f95",
    ".fish",
    ".for",
    ".ftn",
    ".fs",
    ".fsi",
    ".fsx",
    ".gemspec",
    ".go",
    ".groovy",
    ".h",
    ".hh",
    ".hpp",
    ".hrl",
    ".hs",
    ".hxx",
    ".java",
    ".jl",
    ".js",
    ".jsx",
    ".kt",
    ".kts",
    ".lhs",
    ".lisp",
    ".lua",
    ".m",
    ".mjs",
    ".ml",
    ".mli",
    ".mm",
    ".mts",
    ".nim",
    ".odin",
    ".p",
    ".pas",
    ".php",
    ".pl",
    ".pm",
    ".pp",
    ".py",
    ".ps1",
    ".pyi",
    ".pyw",
    ".r",
    ".rake",
    ".rb",
    ".rs",
    ".s",
    ".scala",
    ".scm",
    ".sh",
    ".sol",
    ".st",
    ".svelte",
    ".swift",
    ".t",
    ".tcl",
    ".ts",
    ".tsx",
    ".v",
    ".vb",
    ".vhd",
    ".vhdl",
    ".vbs",
    ".vue",
    ".zig",
    ".zsh",
    ".css",
    ".less",
    ".pcss",
    ".sass",
    ".scss",
    ".sss",
    ".styl",
}
ARCHITECTURE_EXTENSIONS = SOURCE_EXTENSIONS | {
    ".adoc",
    ".avsc",
    ".capnp",
    ".cfg",
    ".conf",
    ".fbs",
    ".gql",
    ".graphql",
    ".ini",
    ".json",
    ".jsonc",
    ".md",
    ".neon",
    ".proto",
    ".rst",
    ".sql",
    ".thrift",
    ".toml",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
}
# Architecture-bearing files include source, IDL/schema, and configuration
# files.  Structural ownership checks intentionally apply to a narrower set:
# metadata and documentation are inventoried, but they are not authored source
# units merely because their suffix is supported by the file walker.
SOURCE_BEARING_IDL_EXTENSIONS = {
    ".avsc",
    ".capnp",
    ".fbs",
    ".gql",
    ".graphql",
    ".proto",
    ".sql",
    ".thrift",
}
SOURCE_BEARING_CONFIG_EXTENSIONS = {
    ".cfg",
    ".conf",
    ".ini",
    ".json",
    ".jsonc",
    ".toml",
    ".xml",
    ".yaml",
    ".yml",
}
SOURCE_BEARING_DIRECTORIES = {
    "app",
    "apps",
    "bench",
    "benches",
    "cmd",
    "components",
    "config",
    "configs",
    "graphql",
    "idl",
    "include",
    "internal",
    "lib",
    "libs",
    "modules",
    "packages",
    "pkg",
    "proto",
    "queries",
    "schema",
    "schemas",
    "script",
    "scripts",
    "source",
    "src",
    "test",
    "tests",
    "tool",
    "tools",
}
DEFAULT_IGNORED_DIRS = {
    ".bundle",
    ".cache",
    ".dart_tool",
    ".direnv",
    ".eggs",
    ".git",
    ".gradle",
    ".hg",
    ".idea",
    ".mypy_cache",
    ".next",
    ".npm",
    ".nuget",
    ".pnpm-store",
    ".pytest_cache",
    ".ruff_cache",
    ".svn",
    ".swiftpm",
    ".tox",
    ".turbo",
    ".venv",
    ".vscode",
    ".yarn",
    "CMakeFiles",
    "Pods",
    "__pycache__",
    "bower_components",
    "node_modules",
    "venv",
}
GENERIC_BUCKETS = {
    "base",
    "common",
    "commons",
    "core",
    "helper",
    "helpers",
    "manager",
    "managers",
    "misc",
    "model",
    "models",
    "service",
    "services",
    "shared",
    "type",
    "types",
    "util",
    "utils",
    "validation",
    "validations",
    "validator",
    "validators",
}
GENERIC_FILENAMES = GENERIC_BUCKETS | {"constants", "factory", "functions", "stuff"}
# A suffix that describes a procedural category rather than a durable
# capability is still a review finding when attached to an owned stem.  Keep
# this set deliberately narrow: domain words such as ``runtime`` or
# ``contract`` are semantic and must not be silently reclassified.
GENERIC_PROCEDURAL_SUFFIXES = {
    "base",
    "commit",
    "common",
    "commons",
    "constants",
    "factory",
    "factories",
    "functions",
    "helper",
    "helpers",
    "impl",
    "manager",
    "managers",
    "misc",
    "model",
    "models",
    "open",
    "reduce",
    "stuff",
    "type",
    "types",
    "util",
    "utils",
    "validation",
    "validations",
    "validator",
    "validators",
}
PROCEDURAL_PHASES = {"commit", "open", "reduce"}
STRUCTURAL_DIRECTORIES = {
    "app",
    "apps",
    "bin",
    "cmd",
    "config",
    "docs",
    "examples",
    "include",
    "lib",
    "libs",
    "main",
    "pkg",
    "script",
    "scripts",
    "src",
    "source",
    "test",
    "tests",
    "tool",
    "tools",
}
TEMPORAL_OR_NUMBERED = re.compile(
    r"(?:^|[-_.])(old|final|backup|copy|temp|tmp|legacy)(?:[-_.]|$)|(?:[-_.]\d+)$",
    re.IGNORECASE,
)
CATEGORY_CHAIN = re.compile(
    r"(?:base|controller|factory|handler|helper|impl|manager|provider|repository|service|util)(?:[-_](?:base|controller|factory|handler|helper|impl|manager|provider|repository|service|util))+",
    re.IGNORECASE,
)
GENERATED_HEADER = re.compile(
    r"^\s*(?://+|#+|/\*+|\*+)\s*(?:@generated\b|code generated\b.*\bdo not edit\b|generated by\b.*\bdo not edit\b|this file (?:is|was) generated\b)",
    re.IGNORECASE,
)
GENERATED_NAME_PATTERNS = (
    "*.designer.cs",
    "*.freezed.dart",
    "*.g.dart",
    "*.gen.*",
    "*.generated.*",
    "*.pb.cc",
    "*.pb.cpp",
    "*.pb.go",
    "*.pb.h",
    "*.pb.hpp",
)
RESERVED_FILES = {
    ".biomeignore",
    ".clippyignore",
    ".eslintignore",
    ".flake8",
    ".gitignore",
    ".golangciignore",
    ".ktlintignore",
    ".mypyignore",
    ".pylintignore",
    ".prettierignore",
    ".pyrightignore",
    ".rubocopignore",
    ".ruffignore",
    ".stylua.toml",
    ".stylelintignore",
    ".swiftlintignore",
    ".tslintignore",
    "agents.md",
    "build.gradle",
    "cargo.toml",
    "changelog.md",
    "cmakelists.txt",
    "composer.json",
    "deno.json",
    "deno.jsonc",
    "description",
    "dockerfile",
    "gemfile",
    "makefile",
    "mypy.ini",
    "namespace",
    "openai.yaml",
    "package.json",
    "packages.lock.json",
    "podfile",
    "pyproject.toml",
    "selene-tests.toml",
    "selene.toml",
    "settings.gradle",
    "settings.xml",
    "skill.md",
    "vim-test.yml",
    "vim.yml",
}
RESERVED_PATTERNS = (
    "tsconfig*.json",
    "*.csproj",
    "*.fsproj",
    "*.vbproj",
    "*.xcodeproj",
)
GO_OS_MARKERS = {
    "aix",
    "android",
    "darwin",
    "dragonfly",
    "freebsd",
    "illumos",
    "ios",
    "js",
    "linux",
    "netbsd",
    "openbsd",
    "plan9",
    "solaris",
    "wasip1",
    "windows",
}
GO_ARCH_MARKERS = {
    "386",
    "amd64",
    "arm",
    "arm64",
    "loong64",
    "mips",
    "mips64",
    "mips64le",
    "mipsle",
    "ppc64",
    "ppc64le",
    "riscv64",
    "s390x",
    "wasm",
}
KOTLIN_PLATFORM_MARKERS = {
    "android",
    "common",
    "ios",
    "js",
    "jvm",
    "linux",
    "native",
    "wasm",
}
JS_LOCKFILES = {
    "bun": ("bun.lock", "bun.lockb"),
    "npm": ("npm-shrinkwrap.json", "package-lock.json"),
    "pnpm": ("pnpm-lock.yaml",),
    "yarn": ("yarn.lock",),
}
SEVERITY_RANK = {"error": 0, "warning": 1, "notice": 2}

# These are policy defaults, not command-line knobs.  The audit API keeps
# keyword arguments for callers that need deterministic diagnostics in tests,
# while the production entry point always uses these values.
SOFT_LINE_THRESHOLD = 450
STRONG_LINE_THRESHOLD = 650
HARD_LINE_THRESHOLD = 800
FLAT_CLUSTER_LIMIT = 12
MICROFILE_MIN_SIBLINGS = 4
MICROFILE_MAX_LINES = 120
