import type { ConfigKeyPair } from "./key-pair.ts";

const providerCacheKeys: readonly ConfigKeyPair[] = [
  ["cargo", "cargo.caching.duration"],
  ["composer", "composer.caching.duration"],
  ["deno", "deno.caching.duration"],
  ["docker", "docker.caching.duration"],
  ["dotnet", "dotnet.caching.duration"],
  ["dub", "dub.caching.duration"],
  ["golang", "golang.caching.duration"],
  ["maven", "maven.caching.duration"],
  ["npm", "npm.caching.duration"],
  ["pub", "pub.caching.duration"],
  ["pypi", "pypi.caching.duration"],
  ["ruby", "ruby.caching.duration"],
  ["hex", "hex.caching.duration"],
  ["opam", "opam.caching.duration"],
  ["hackage", "hackage.caching.duration"],
  ["julia", "julia.caching.duration"],
  ["cran", "cran.caching.duration"],
  ["conan", "conan.caching.duration"],
  ["vcpkg", "vcpkg.caching.duration"],
  ["swift", "swift.caching.duration"],
  ["zig", "zig.caching.duration"],
  ["nim", "nim.caching.duration"],
  ["luarocks", "luarocks.caching.duration"],
  ["cpan", "cpan.caching.duration"],
  ["haxelib", "haxelib.caching.duration"],
  ["terraform", "terraform.caching.duration"],
  ["helm", "helm.caching.duration"],
  ["ansible", "ansible.caching.duration"],
  ["bazel", "bazel.caching.duration"],
  ["nix", "nix.caching.duration"],
  ["kustomize", "kustomize.caching.duration"],
  ["unity", "unity.caching.duration"],
  ["cocoapods", "cocoapods.caching.duration"],
  ["cpp", "cpp.caching.duration"],
  ["github", "github.caching.duration"],
] as const;

const dependencyPropertyKeys: readonly ConfigKeyPair[] = [
  ["cargo", "cargo.dependencyProperties"],
  ["composer", "composer.dependencyProperties"],
  ["deno", "deno.dependencyProperties"],
  ["dotnet", "dotnet.dependencyProperties"],
  ["dub", "dub.dependencyProperties"],
  ["maven", "maven.dependencyProperties"],
  ["npm", "npm.dependencyProperties"],
  ["pnpm", "pnpm.dependencyProperties"],
  ["pub", "pub.dependencyProperties"],
  ["pypi", "pypi.dependencyProperties"],
  ["hex", "hex.dependencyProperties"],
  ["opam", "opam.dependencyProperties"],
  ["hackage", "hackage.dependencyProperties"],
  ["julia", "julia.dependencyProperties"],
  ["cran", "cran.dependencyProperties"],
  ["conan", "conan.dependencyProperties"],
  ["vcpkg", "vcpkg.dependencyProperties"],
  ["swift", "swift.dependencyProperties"],
  ["zig", "zig.dependencyProperties"],
  ["nim", "nim.dependencyProperties"],
  ["luarocks", "luarocks.dependencyProperties"],
  ["cpan", "cpan.dependencyProperties"],
  ["haxelib", "haxelib.dependencyProperties"],
  ["terraform", "terraform.dependencyProperties"],
  ["helm", "helm.dependencyProperties"],
  ["ansible", "ansible.dependencyProperties"],
  ["bazel", "bazel.dependencyProperties"],
  ["nix", "nix.dependencyProperties"],
  ["kustomize", "kustomize.dependencyProperties"],
  ["unity", "unity.dependencyProperties"],
  ["cocoapods", "cocoapods.dependencyProperties"],
  ["cpp", "cpp.dependencyProperties"],
  ["github", "github.dependencyProperties"],
] as const;

type FilePatternKey = readonly [
  ecosystem: string,
  key: string,
  languages: readonly string[],
  excludePatterns?: readonly string[],
];

const filePatternKeys: readonly FilePatternKey[] = [
  ["cargo", "cargo.files", ["toml"]],
  ["composer", "composer.files", ["json", "jsonc"]],
  ["deno", "deno.files", ["json", "jsonc"]],
  ["docker", "docker.files", ["dockerfile", "dockercompose", "yaml"]],
  [
    "dotnet",
    "dotnet.files",
    ["xml", "json", "jsonc", "plaintext"],
    ["**/obj/**"],
  ],
  ["dub", "dub.files", ["json", "jsonc", "plaintext"]],
  ["golang", "golang.files", ["go.mod"]],
  [
    "maven",
    "maven.files",
    ["xml", "groovy", "kotlin", "toml", "scala", "clojure"],
  ],
  ["npm", "npm.files", ["json", "jsonc", "json5", "yaml"]],
  ["pnpm", "pnpm.files", ["yaml"]],
  ["pypi", "pypi.files", ["toml", "pip-requirements", "plaintext"]],
  ["pub", "pub.files", ["yaml"]],
  ["ruby", "ruby.files", ["ruby", "plaintext"]],
  ["hex", "hex.files", ["elixir", "erlang", "toml", "plaintext"]],
  ["opam", "opam.files", ["plaintext"]],
  ["hackage", "hackage.files", ["plaintext", "yaml"]],
  ["julia", "julia.files", ["toml"]],
  ["cran", "cran.files", ["plaintext", "json"]],
  ["conan", "conan.files", ["plaintext", "python"]],
  ["vcpkg", "vcpkg.files", ["json", "jsonc"]],
  ["swift", "swift.files", ["swift"]],
  ["zig", "zig.files", ["zig"]],
  ["nim", "nim.files", ["nim", "plaintext"]],
  ["luarocks", "luarocks.files", ["lua"]],
  ["cpan", "cpan.files", ["perl", "plaintext"]],
  ["haxelib", "haxelib.files", ["json", "jsonc"]],
  ["terraform", "terraform.files", ["terraform", "hcl", "plaintext"]],
  ["helm", "helm.files", ["yaml"]],
  ["ansible", "ansible.files", ["yaml"]],
  ["bazel", "bazel.files", ["starlark", "plaintext"]],
  ["nix", "nix.files", ["nix"]],
  ["kustomize", "kustomize.files", ["yaml"]],
  ["unity", "unity.files", ["json", "jsonc"]],
  ["cocoapods", "cocoapods.files", ["ruby", "plaintext"]],
  [
    "cpp",
    "cpp.files",
    ["cmake", "lua", "meson", "ini", "starlark", "plaintext"],
  ],
  ["github", "github.files", ["yaml"]],
] as const;

function enabledFilePatternKeys(
  enabledProviders: readonly string[] | undefined,
): readonly FilePatternKey[] {
  if (!enabledProviders || enabledProviders.length === 0) {
    return filePatternKeys;
  }

  const enabled = new Set(enabledProviders);
  return filePatternKeys.filter(([ecosystem]): boolean =>
    enabled.has(ecosystem),
  );
}

const providerStrictSslKeys: readonly ConfigKeyPair[] = [
  ["cargo", "cargo.http.strictSSL"],
  ["composer", "composer.http.strictSSL"],
  ["deno", "deno.http.strictSSL"],
  ["docker", "docker.http.strictSSL"],
  ["dotnet", "dotnet.http.strictSSL"],
  ["dub", "dub.http.strictSSL"],
  ["golang", "golang.http.strictSSL"],
  ["maven", "maven.http.strictSSL"],
  ["pub", "pub.http.strictSSL"],
  ["pypi", "pypi.http.strictSSL"],
  ["ruby", "ruby.http.strictSSL"],
  ["hex", "hex.http.strictSSL"],
  ["opam", "opam.http.strictSSL"],
  ["hackage", "hackage.http.strictSSL"],
  ["julia", "julia.http.strictSSL"],
  ["cran", "cran.http.strictSSL"],
  ["conan", "conan.http.strictSSL"],
  ["vcpkg", "vcpkg.http.strictSSL"],
  ["swift", "swift.http.strictSSL"],
  ["zig", "zig.http.strictSSL"],
  ["nim", "nim.http.strictSSL"],
  ["luarocks", "luarocks.http.strictSSL"],
  ["cpan", "cpan.http.strictSSL"],
  ["haxelib", "haxelib.http.strictSSL"],
  ["terraform", "terraform.http.strictSSL"],
  ["helm", "helm.http.strictSSL"],
  ["ansible", "ansible.http.strictSSL"],
  ["bazel", "bazel.http.strictSSL"],
  ["nix", "nix.http.strictSSL"],
  ["kustomize", "kustomize.http.strictSSL"],
  ["unity", "unity.http.strictSSL"],
  ["cocoapods", "cocoapods.http.strictSSL"],
  ["cpp", "cpp.http.strictSSL"],
  ["github", "github.http.strictSSL"],
] as const;

const prereleaseTagKeys: readonly ConfigKeyPair[] = [
  ["cargo", "cargo.prereleaseTagFilter"],
  ["composer", "composer.prereleaseTagFilter"],
  ["deno", "deno.prereleaseTagFilter"],
  ["dotnet", "dotnet.prereleaseTagFilter"],
  ["dub", "dub.prereleaseTagFilter"],
  ["golang", "golang.prereleaseTagFilter"],
  ["maven", "maven.prereleaseTagFilter"],
  ["npm", "npm.prereleaseTagFilter"],
  ["pypi", "pypi.prereleaseTagFilter"],
  ["pub", "pub.prereleaseTagFilter"],
  ["ruby", "ruby.prereleaseTagFilter"],
  ["hex", "hex.prereleaseTagFilter"],
  ["opam", "opam.prereleaseTagFilter"],
  ["hackage", "hackage.prereleaseTagFilter"],
  ["julia", "julia.prereleaseTagFilter"],
  ["cran", "cran.prereleaseTagFilter"],
  ["conan", "conan.prereleaseTagFilter"],
  ["vcpkg", "vcpkg.prereleaseTagFilter"],
  ["swift", "swift.prereleaseTagFilter"],
  ["zig", "zig.prereleaseTagFilter"],
  ["nim", "nim.prereleaseTagFilter"],
  ["luarocks", "luarocks.prereleaseTagFilter"],
  ["cpan", "cpan.prereleaseTagFilter"],
  ["haxelib", "haxelib.prereleaseTagFilter"],
  ["terraform", "terraform.prereleaseTagFilter"],
  ["helm", "helm.prereleaseTagFilter"],
  ["ansible", "ansible.prereleaseTagFilter"],
  ["bazel", "bazel.prereleaseTagFilter"],
  ["nix", "nix.prereleaseTagFilter"],
  ["kustomize", "kustomize.prereleaseTagFilter"],
  ["unity", "unity.prereleaseTagFilter"],
  ["cocoapods", "cocoapods.prereleaseTagFilter"],
  ["cpp", "cpp.prereleaseTagFilter"],
  ["github", "github.prereleaseTagFilter"],
] as const;

const registryUrlKeys: readonly ConfigKeyPair[] = [
  ["cargo", "cargo.apiUrl"],
  ["composer", "composer.apiUrl"],
  ["dub", "dub.apiUrl"],
  ["golang", "golang.apiUrl"],
  ["maven", "maven.apiUrl"],
  ["pypi", "pypi.apiUrl"],
  ["pub", "pub.apiUrl"],
  ["ruby", "ruby.apiUrl"],
  ["hex", "hex.apiUrl"],
  ["opam", "opam.apiUrl"],
  ["hackage", "hackage.apiUrl"],
  ["julia", "julia.apiUrl"],
  ["cran", "cran.apiUrl"],
  ["conan", "conan.apiUrl"],
  ["vcpkg", "vcpkg.apiUrl"],
  ["swift", "swift.apiUrl"],
  ["zig", "zig.apiUrl"],
  ["nim", "nim.apiUrl"],
  ["luarocks", "luarocks.apiUrl"],
  ["cpan", "cpan.apiUrl"],
  ["haxelib", "haxelib.apiUrl"],
  ["terraform", "terraform.apiUrl"],
  ["helm", "helm.apiUrl"],
  ["ansible", "ansible.apiUrl"],
  ["bazel", "bazel.apiUrl"],
  ["nix", "nix.apiUrl"],
  ["unity", "unity.apiUrl"],
  ["cocoapods", "cocoapods.apiUrl"],
  ["cpp", "cpp.apiUrl"],
  ["github", "github.apiUrl"],
] as const;

export {
  dependencyPropertyKeys,
  enabledFilePatternKeys,
  filePatternKeys,
  prereleaseTagKeys,
  providerCacheKeys,
  providerStrictSslKeys,
  registryUrlKeys,
};
