use serde::{Deserialize, Serialize};

#[repr(usize)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Ecosystem {
    Cargo,
    Composer,
    Deno,
    Dotnet,
    Docker,
    Dub,
    Go,
    Maven,
    Npm,
    Python,
    Pub,
    Ruby,
    Hex,
    Opam,
    Hackage,
    Julia,
    Cran,
    Conan,
    Vcpkg,
    Swift,
    Zig,
    Nim,
    LuaRocks,
    Cpan,
    Haxelib,
    Terraform,
    Helm,
    AnsibleGalaxy,
    Bazel,
    Nix,
    Unity,
    CocoaPods,
    Cpp,
    GitHub,
}

pub const ALL_ECOSYSTEMS: &[Ecosystem] = &[
    Ecosystem::Cargo,
    Ecosystem::Composer,
    Ecosystem::Deno,
    Ecosystem::Dotnet,
    Ecosystem::Docker,
    Ecosystem::Dub,
    Ecosystem::Go,
    Ecosystem::Maven,
    Ecosystem::Npm,
    Ecosystem::Python,
    Ecosystem::Pub,
    Ecosystem::Ruby,
    Ecosystem::Hex,
    Ecosystem::Opam,
    Ecosystem::Hackage,
    Ecosystem::Julia,
    Ecosystem::Cran,
    Ecosystem::Conan,
    Ecosystem::Vcpkg,
    Ecosystem::Swift,
    Ecosystem::Zig,
    Ecosystem::Nim,
    Ecosystem::LuaRocks,
    Ecosystem::Cpan,
    Ecosystem::Haxelib,
    Ecosystem::Terraform,
    Ecosystem::Helm,
    Ecosystem::AnsibleGalaxy,
    Ecosystem::Bazel,
    Ecosystem::Nix,
    Ecosystem::Unity,
    Ecosystem::CocoaPods,
    Ecosystem::Cpp,
    Ecosystem::GitHub,
];

const ECOSYSTEM_CONFIG_NAMES: &[(&str, Ecosystem)] = &[
    ("cargo", Ecosystem::Cargo),
    ("composer", Ecosystem::Composer),
    ("deno", Ecosystem::Deno),
    ("dotnet", Ecosystem::Dotnet),
    ("docker", Ecosystem::Docker),
    ("kustomize", Ecosystem::Docker),
    ("dub", Ecosystem::Dub),
    ("go", Ecosystem::Go),
    ("golang", Ecosystem::Go),
    ("maven", Ecosystem::Maven),
    ("hex", Ecosystem::Hex),
    ("beam", Ecosystem::Hex),
    ("opam", Ecosystem::Opam),
    ("ocaml", Ecosystem::Opam),
    ("hackage", Ecosystem::Hackage),
    ("haskell", Ecosystem::Hackage),
    ("julia", Ecosystem::Julia),
    ("cran", Ecosystem::Cran),
    ("r", Ecosystem::Cran),
    ("conan", Ecosystem::Conan),
    ("vcpkg", Ecosystem::Vcpkg),
    ("swift", Ecosystem::Swift),
    ("zig", Ecosystem::Zig),
    ("nim", Ecosystem::Nim),
    ("luarocks", Ecosystem::LuaRocks),
    ("lua", Ecosystem::LuaRocks),
    ("cpan", Ecosystem::Cpan),
    ("perl", Ecosystem::Cpan),
    ("haxelib", Ecosystem::Haxelib),
    ("haxe", Ecosystem::Haxelib),
    ("terraform", Ecosystem::Terraform),
    ("opentofu", Ecosystem::Terraform),
    ("tofu", Ecosystem::Terraform),
    ("helm", Ecosystem::Helm),
    ("ansible", Ecosystem::AnsibleGalaxy),
    ("ansible-galaxy", Ecosystem::AnsibleGalaxy),
    ("galaxy", Ecosystem::AnsibleGalaxy),
    ("bazel", Ecosystem::Bazel),
    ("bzlmod", Ecosystem::Bazel),
    ("nix", Ecosystem::Nix),
    ("unity", Ecosystem::Unity),
    ("cocoapods", Ecosystem::CocoaPods),
    ("cpp", Ecosystem::Cpp),
    ("c-cpp", Ecosystem::Cpp),
    ("c++", Ecosystem::Cpp),
    ("cmake", Ecosystem::Cpp),
    ("xmake", Ecosystem::Cpp),
    ("meson", Ecosystem::Cpp),
    ("bun", Ecosystem::Npm),
    ("npm", Ecosystem::Npm),
    ("pnpm", Ecosystem::Npm),
    ("pypi", Ecosystem::Python),
    ("python", Ecosystem::Python),
    ("pub", Ecosystem::Pub),
    ("ruby", Ecosystem::Ruby),
    ("github", Ecosystem::GitHub),
];

const ECOSYSTEM_CONFIG_NAMESPACES: &[&str] = &[
    "cargo",
    "composer",
    "deno",
    "dotnet",
    "docker",
    "dub",
    "golang",
    "maven",
    "npm",
    "pypi",
    "pub",
    "ruby",
    "hex",
    "opam",
    "hackage",
    "julia",
    "cran",
    "conan",
    "vcpkg",
    "swift",
    "zig",
    "nim",
    "luarocks",
    "cpan",
    "haxelib",
    "terraform",
    "helm",
    "ansible",
    "bazel",
    "nix",
    "unity",
    "cocoapods",
    "cpp",
    "github",
];

pub fn ecosystem_from_config_name(name: &str) -> Option<Ecosystem> {
    ECOSYSTEM_CONFIG_NAMES
        .iter()
        .find_map(|(candidate, ecosystem)| (*candidate == name).then_some(*ecosystem))
}

pub fn ecosystem_config_namespace(ecosystem: Ecosystem) -> &'static str {
    ECOSYSTEM_CONFIG_NAMESPACES[ecosystem as usize]
}

pub fn ecosystem_provider_id(ecosystem: Ecosystem) -> &'static str {
    match ecosystem {
        Ecosystem::Go => "go",
        Ecosystem::Python => "python",
        _ => ecosystem_config_namespace(ecosystem),
    }
}

#[cfg(test)]
#[path = "ecosystem/tests.rs"]
mod tests;
